spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:3306/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    defer-datasource-initialization: true
  jackson:
    deserialization:
      fail-on-unknown-properties: true
    property-naming-strategy: SNAKE_CASE
  sql:
    init:
      mode: always

oauth:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    redirect-uri: ${KAKAO_REDIRECT_URI}
    token-uri: https://kauth.kakao.com/oauth/token
    user-info-uri: https://kapi.kakao.com/v2/user/me

naver:
  shopping:
    client-id: ${NAVER_CLIENT_ID}
    client-secret: ${NAVER_CLIENT_SECRET}
    base-url: https://openapi.naver.com/v1/search/shop.json

jwt:
  secret: ${JWT_SECRET}
  access-token-expire-time: ${JWT_ACCESS_EXPIRE:3600000}     # 1시간
  refresh-token-expire-time: ${JWT_REFRESH_EXPIRE:1209600000} # 2주
